version: 2
jobs:
  test_local:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    parallelism: 4
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Test home feature
          command: ./gradlew :features:home:presentation:testDebugUnitTest
      - run:
          name: Test settings feature
          command: ./gradlew :features:settings:presentation:testDebugUnitTest
      - run:
          name: Test videos feature
          command: ./gradlew :features:videos:presentation:testDebugUnitTest :features:videos:data:tesDebugUnitTest :features:videos:featureTest:testDebugUnitTest
      - run:
          name: Test pictures feature
          command: ./gradlew :features:pictures:presentation:testDebugUnitTest :features:pictures:data:testDebugUnitTest :features:pictures:featureTest:testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  e2e_tests:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Assemble debug test apk
          command: ./gradlew :app:assembleDebug :app:assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \
              --type instrumentation \
              --app app/build/outputs/apk/debug/app-debug.apk \
              --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --device model=greatlte,version=28,locale=en,orientation=portrait
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_local
      - e2e_tests
